language: nodejs

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - npm run docs
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: c18cc1bd651c82cddf8b5b002788950917b9a452
    on:
      tags: true
  - provider: releases
    api_key: c18cc1bd651c82cddf8b5b002788950917b9a452
    file_glob: true
    file: "complete-round-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "gavin@gavinsykes.uk"
    api_key: 20e81727-2690-42d2-ab29-3af619a744af
    on:
      tags: true
